### ISSUE TITLE
PWM intruder unlock does not interface with Ping Identity (UnboundID) 

### ISSUE THREAD

**Issue by dcozzy** [pwm-project/pwm#228]
We are moving from eDirectory to Ping – there are accounts that have Intruder lockout engaged. Is there a way to lock these accounts in Ping? We presently have an LDAP driver in eDirectory to migrate, modify, create, etc.. users in Ping and will continue to use this until full cutover to Ping. Additionally, we are using PWM on the Ping side. Is there a way to have PWM unlock an account within Ping?

**Comment by jcombs-pointblue** [comment]
This is not really a PWM question. The issue is translating the intruderLockout in eDir to how it is represented in UnboundID. I haven’t looked at this specifically but it should be possible. Of course, there is also the issue of setting PWM to understand the lockout in UID.

Unfortunately, intruder lockout is not something that was ever standardized as part of LDAP.

JC

**Comment by dcozzy** [comment]
Thank you JC.
We were able to define an attribute between eDir and Ping, write a bit of code around the attribute on the eDir driver and then using the Help Desk Actor Actions in PWM, created a new action in place of the existing Unlock. Works like a champ!
