### ISSUE TITLE
Allow using help desk search function while people search module is disabled

### ISSUE THREAD

**Issue by watery** [pwm-project/pwm#331]
If I disable the people search module, the search functionality in help desk gets disabled as well, returning "Service not available".

**Comment by joswhite** [comment]
This is a bug. It was introduced by some additions to the helpdesk module and we are currently working on fixing it on the helpdesk-api branch. If needed, for now you can revert back to the commit before the bug was introduced, [13d482a7026b699b04d462651a5f25795ba5cd07](https://github.com/pwm-project/pwm/tree/13d482a7026b699b04d462651a5f25795ba5cd07)

**Comment by joswhite** [comment]
Fixed by [5197577b73d70527db504888107ee9df305236e4](https://github.com/pwm-project/pwm/tree/5197577b73d70527db504888107ee9df305236e4).

**Comment by watery** [comment]
Great! Thank you!
