### ISSUE TITLE
Releases, Versions & Notes

### ISSUE THREAD

**Issue by BloodyIron** [pwm-project/pwm#510]
I see that this github project has zero releases, yet there is a build repo.

I've been aware of (and implemented) PWM for about 5 years now, and based on the build history, I honestly can't tell what has changed over the years in specific versions.

Can we please get this project to have actual releases with notes in the release section of the GitHub project? This way we know what each version change has, and can rapidly find where to grab the new files.

Please? :)

**Comment by alerque** [comment]
This is a huge problem for package managers too. I've been trying since 2016 to get this [packaged for Arch Linux](https://aur.archlinux.org/packages/pwm) and not having release tags is _still_ a blocker to that effort.

**Comment by alerque** [comment]
@jrivard It seems you've declined this issue several times now. Please reconsider your answer because this is hindering adoption and making things unnecessarily difficult for users. I'd be happy to have a technical discussion about why this is needed if you don't understand why this is needed downstream.

**Comment by BloodyIron** [comment]
Well, hopefully we can get releases and release notes, because honestly, it's what every quality software group does on GitHub (and elsewhere). PWM is a good tool, and I want to see this from the devs too.

**Comment by jrivard** [comment]
Regular releases, support, documentation and update tracking is done via the Self Service Password Reset product here: https://www.microfocus.com/en-us/products/netiq-self-service-password-reset

**Comment by alerque** [comment]
Oh I see, you mean you _don't want_ distros to be able to package and distribute this easily because it would cut into business so you are deliberately making the process harder for the FOSS world. Well phooey, that sucks. It doesn't have to be this way you know, selling support and hosting for an open source product can work, but you can't get there by trying to cut contributors off at the knees.

**Comment by jrivard** [comment]
Sorry you feel the way, but that's not case at all.  The problem is that regular release cycles, packages and most critically QA/integration testing are thus far missing from the open source community.  If the community wants to step up and provide quality testing and release management, I'm all for it and there's nothing stopping it.   I'm not sure how contributors are being cut off, anyone can contribute.   Rather the commercial development is funding a substantial part of the codebase that otherwise wouldn't exist.

**Comment by alerque** [comment]
You make this sound more complicated than it needs to be. We weren't requesting you to make packages or commit to regular release cycles or anything. All we want is for you to use `git tag` to note the commit points at which the version number currently buried deep in the code itself changes (or the most logical place after that to actually build that version number form) so that OTHER PEOPLE can work on making packages

And yes, other people making packages for various distros will definitely have and affect on adoption and eventually on community contribution levels too.

**Comment by jrivard** [comment]
There's a branch for 1.9 release, which is effectively the last "stable" release of PWM, otherwise the version number for 2.0 in master hasn't changed since the 1.9 release, and it's marked as 2.0-SNAPSHOT because its got unstable features.  The branch should be good enough to pull from?  I'm not familiar with git tag but I'll look into it.

**Comment by alerque** [comment]
I apologist. I assumed more git expertise and familiarity with general usage practice that I should have. It's not an offense not to know how to do something. The 2+ years of closing issues related to this makes it feel a lot more deliberate, but if the issue is just you don't know how to do it I'm sure there are a few of us out here that would be glad to help.
