### ISSUE TITLE
Localdblogger excess records are not purged

### ISSUE THREAD

**Issue by Cris70** [pwm-project/pwm#707]
**Describe the bug**
PWM Health Check reports that LocalDBLogger has records in excess with respect to the maximum configured age.
It also reports that "Excess records are being purged". But they are not purged, as every day the report shows older messages.

**To Reproduce**
N/A

**Expected behavior**
I would expect for PWM to purge the excess records, as it reports in the Health Check summary.

**Screenshots**
![image](https://github.com/pwm-project/pwm/assets/5107224/26859162-a0c6-4736-aa87-39d6ff616f98)

**Desktop (please complete the following information):**
 - OS: Linux openSUSE Tumbleweed
 - Browser: Firefox
 - Version:  PWM 2.0.6

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jrivard** [comment]
Wasn't able to reproduce after testing with database export supplied by reporter, as well as issue seems to have resolved itself with reporter's system.   Please re-open if this issue returns.

**Comment by msoltyspl** [comment]
For the record, I've had the same issue since I don't know how long. After roughly that 1 month passes, the only workaround I found is to export config, wipe db, reimport config.

![image](https://github.com/user-attachments/assets/8e68addd-a558-4434-a18b-4601b0125286)

I also did some quick test - changed the log's max age (`events.pwmDB.maxAge`) in the configuration and restarted the service, but it doesn't look like anything is being purged.

![image](https://github.com/user-attachments/assets/bcbd5da4-d730-45a2-86ef-22cd4b458418)

**Comment by jrivard** [comment]
@msoltyspl If you'd like to send me an export of your LocalDB using the instructions here:

https://groups.google.com/g/pwm-general/c/y4FctbtGNzo/m/glqcOtrTCgAJ

I can try again to reproduce this.

**Comment by msoltyspl** [comment]
Will do that if it gets back to this issue again, I've just reset the db to silence checks.

**Comment by Cris70** [comment]
I still have this problem, but I've learned to live with it.
First of all: it seems it doesn't do any harm if I let the LocalDBLogger grow well over the configures limit.
Second: it seems sometimes, somehow, LocalDBLogger records are actually purged, but I never managed to reliably reproduce this behavior.
Sometimes it seems that simply restarting the docker image will do the trick. Other times it takes a full restart of the host VM. And sometimes nothing will convince it to do the purge.
Presently, my oldest LocalDBLogger event log record is 99d and counting.
